### ISSUE TITLE
Add repo website here on GitHub

### ISSUE THREAD

**Issue by szepeviktor** [tomjn/p2020#4]
Please set `https://wpcom-themes.svn.automattic.com/p2020/` in the top right corner with the cog icon.

**Comment by tomjn** [comment]
I've added it under about but it isn't clickable. I consider this theme technically superior except that P2tenberg is missing, this is a fork not a mirror until such a time as Automattic cleans up their code

**Comment by szepeviktor** [comment]
Thank you.
