### ISSUE TITLE
Blank screen on comment

### ISSUE THREAD

**Issue by nguyentrongtanhlu** [tomjn/p2020#6]
hi tomjn,
i very like and used p2020 theme of you. it is great but had a bug: when someone writes a comment on each post => the site is bug (screen is white)
i hope you guides me fix bug for theme p2020.
Many thanks

**Comment by tomjn** [comment]
Keep in mind I didn't write the theme, I just made some adjustments so it would load outside of a wp.com context. Do you have the PHP error message for this? **Without it I cannot help you.**

**Comment by nguyentrongtanhlu** [comment]
thanks you, i very like this theme, do you know news for p2020theme used on wordpress.org as themes: 2020, 2019 of automattic?
thanks you so much

**Comment by tomjn** [comment]
> thanks you, i very like this theme, do you know news for p2020theme used on wordpress.org as themes:

It's extremely unlikely that P2020 will ever appear on .org. P2 appeared on the .org theme repository, but P2 breathe didn't, neither did the O2 plugin needed to make that theme or P2020 work.

They have indicated they would like to though, but you would need to ask them. Given that they said the same thing about P2 Breathe, I can believe they have the desire but not the bandwidth/time. It could be years, if it happens at all.

> 2020, 2019 of automattic?

WordPress.org is not an Automattic product, and while the default themes have some involvement, they aren't owned or maintained by Automattic.

**Comment by tomjn** [comment]
@nguyentrongtanhlu can you confirm you had activated the O2 plugin before commenting? Did you get the PHP error message?

**Comment by nguyentrongtanhlu** [comment]
![Capture](https://user-images.githubusercontent.com/64125217/101339463-0e95d780-38b1-11eb-84e1-3349552a27c8.PNG)
this site after someoe writers comment.
i deleted this comment and this site works normally

**Comment by tomjn** [comment]
But do you have the error message? I need the error message

**Comment by nguyentrongtanhlu** [comment]
detail bug this video: https://thehrmblog.com/fix-bug/

help me please,

**Comment by tomjn** [comment]
@nguyentrongtanhlu I understood the description of the problem, but I keep asking you for the PHP fatal error message, and you keep ignoring my question. I ***need*** the error message, without the error message I cannot help. I've asked 3 times now:

> Keep in mind I didn't write the theme, I just made some adjustments so it would load outside of a wp.com context. Do you have the PHP error message for this? Without it I cannot help you.

> Did you get the PHP error message?

> But do you have the error message? I need the error message

If you don't have it, if you don't know what it is, if you can't find it, I need to know that too. _Do not ignore the question. This is unavoidable mandatory required information._ The problem cannot be fixed without it. If you keep ignoring this question I will close the issue.

**Comment by nguyentrongtanhlu** [comment]
Hi you,
I do not receive the error PHP message

**Comment by tomjn** [comment]
I found the PHP fatal error message myself. This could have been fixed 2 days ago if you had provided it.

> I do not receive the error PHP message

There is always a PHP error message, just because it isn't in the browser doesn't mean it wasn't logged somewhere. Even the complete absence of the message would have been useful information.

**Comment by nguyentrongtanhlu** [comment]
sorry  you, actually I didn't know that was an error, Anyway, thank you very much

**Comment by nguyentrongtanhlu** [comment]
hi @tomjn , i reset all my site (http://thehrmblog.com/) via plugin WP reset and result that fixed this bug and active normal.
Thanks you very much.
